server:
  port: 8090
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WorkFolio?useSSL=false
    username: root
    password: root
    
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
    show-sql: true        
    generate-ddl: true                      
